name: Publicar Página a Surge.sh
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Configurar Surge.sh
        npm install --global surge
        surge token <SURGE_API_KEY> 

        # Desplegar en Surge.sh
        surge --project ./ --domain <SURGE_SUBDOMAIN>.surge.sh 
